Ref [TASK][53322] Get api genres and display screen
awesome-academy/THE-MOVIE-DB pull request #4
Opened 2022-09-28 08:53 UTC by ndt0409

## Related Tickets
- [#Task 53322: Get api genres and display screen](https://edu-redmine.sun-asterisk.vn/issues/53322)
## WHAT
- 
## Evidence (Screenshot or Video)
![Screenshot 2022-09-28 110746](https://user-images.githubusercontent.com/60254566/192735164-d6b47430-cbb8-4cca-a6fb-f6498c876979.png)
## Review Checklist

Category | View Point | Description | Self review | Reviewer2 (name)
--- | --- | --- | --- | ---
Conventions | Sun* coding conventions | https://sal.vn/WtYPAy |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Conventions | Kotlin coding conventions | https://kotlinlang.org/docs/coding-conventions.html |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Redmine | Sun* Redmine working process  | https://sal.vn/piPoQn |<li>- [ ] yes</li>|<li>- [ ] yes</li>  

## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(List gem, library third party add new)*

*(Other notes)*

2022-09-29 01:44 UTC, minhnn-1279 commented on app/src/main/java/com/ndt/themoviedb/data/repository/MovieRepository.kt
> +class MovieRepository private constructor(
không cần private constructor đâu a ơi

2022-09-29 01:44 UTC, minhnn-1279 commented on app/src/main/java/com/ndt/themoviedb/data/source/MovieDataSource.kt
> +    interface Local
nếu không cần thì remove a nhé

2022-09-29 01:44 UTC, minhnn-1279 commented on app/src/main/java/com/ndt/themoviedb/data/source/remote/response/GenresResponse.kt
> +data class GenresResponse(var list: List<Genres>) {
cái này để val chứ a ơi :v với a dùng mutable list sau mình clear vs add all data

2022-09-29 01:44 UTC, minhnn-1279 commented on app/src/main/java/com/ndt/themoviedb/data/source/remote/response/MoviesResponse.kt
> +data class MoviesResponse(var movieResultPage: MovieResultPage, var list: List<Movie>) {
đây nữa a nhé

2022-09-29 01:44 UTC, minhnn-1279 commented on app/src/main/java/com/ndt/themoviedb/ui/base/BaseAdapter.kt
> +    @SuppressLint("NotifyDataSetChanged")
bỏ suppress lint đi a nhé

2022-09-29 01:44 UTC, minhnn-1279 commented on app/src/main/java/com/ndt/themoviedb/ui/home/HomeFragment.kt
> +    private lateinit var presenter: HomeContract.Presenter
cái này để by lazy nhé a để chống gán lại presenter

2022-09-29 01:44 UTC, minhnn-1279 commented on gradle.properties
> +API_KEY=e49c081f7e07e299deda892eeb0c0f75
https://viblo.asia/p/cac-thu-thuat-de-giau-secret-keypassword-khoi-source-control-va-ung-dung-voi-ci-trong-lap-trinh-android-PwRGgmOnkEd

Chỗ này skip working tree file này a nhé

2022-10-03 08:38 UTC, daolq-2712 requested changes
Pls check my comments!

2022-10-03 08:38 UTC, daolq-2712 commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```suggestion
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    
```

2022-10-03 08:38 UTC, daolq-2712 commented on app/src/main/java/com/ndt/themoviedb/data/source/remote/fetchjson/ParseDataToObject.kt
> +        val list = mutableListOf<Movie>()
```suggestion
        val movies = mutableListOf<Movie>()
```

2022-10-03 08:38 UTC, daolq-2712 commented on app/src/main/java/com/ndt/themoviedb/data/source/remote/fetchjson/ParseDataToObject.kt
> +        val list = mutableListOf<Genres>()
```suggestion
        val listGene = mutableListOf<Genres>()
```

2022-10-03 08:38 UTC, daolq-2712 commented on app/src/main/java/com/ndt/themoviedb/data/source/remote/response/MoviesResponse.kt
> +data class MoviesResponse(val movieResultPage: MovieResultPage, val mutableList: MutableList<Movie>) {
```suggestion
data class MoviesResponse(val movieResultPage: MovieResultPage, val listMovie: MutableList<Movie>) {
```

2022-10-03 08:38 UTC, daolq-2712 commented on app/src/main/java/com/ndt/themoviedb/data/source/remote/response/GenresResponse.kt
> +data class GenresResponse(val mutableList: MutableList<Genres>) {
```suggestion
data class GenresResponse(val listGene: MutableList<Genres>) {
```

2022-10-03 08:38 UTC, daolq-2712 commented on app/src/main/java/com/ndt/themoviedb/ui/home/HomeFragment.kt
> +        Timer().scheduleAtFixedRate(object : TimerTask() {
xử lý leak memory

2022-10-03 08:38 UTC, daolq-2712 commented on app/src/main/java/com/ndt/themoviedb/ui/home/HomePresenter.kt
> +        getGenres()
gọi ở onStart của view

2022-10-03 08:38 UTC, daolq-2712 commented on app/src/main/java/com/ndt/themoviedb/ui/home/adapter/SliderViewPagerAdapter.kt
> +    private val list = arrayListOf<Movie>()
khai báo biến tường minh

2022-10-03 08:38 UTC, daolq-2712 commented on app/src/main/java/com/ndt/themoviedb/ui/home/adapter/SliderViewPagerAdapter.kt
> +        GetImageAsyncTask(
xử lý leak memory

2022-10-06 02:53 UTC, minhnn-1279 approved these changes

2022-10-06 04:58 UTC, merged